### ISSUE TITLE
Allow prepend and append file contents during scaffold process

### ISSUE THREAD

**Issue by jkribeiro** [drupal-composer/drupal-scaffold#51] opened 2016-11-09 12:30 UTC
Hi,

Would be interesting to have an extra feature to be able to "prepend" and "append" file content to another file.

**Use Case:**
Let's suppose that I want to use the D.O. version of the `.htaccess`, provided by drupal-scaffold, and add to this file some custom htaccess logic during the scaffolding process.
The same use case for `settings.php`, I want to use the native version and append some extra confs.

Is different from the `include` option.

The config could be something like this:

```
{
  "extra": {
    "drupal-scaffold": {
      "prepend-content": [
        "/local/path/htaccess.my.conf": ".htaccess",
        "..."
      ],
      "append-content": [
        "/local/path/settings.conf.my.php": "sites/default/settings.php",
        "..."
      ]
    }
  }
}
```

Do you think it would be interesting to have?
I would be glad to send a PR, if positive case.

**Comment by greg-1-anderson** [comment] 2017-03-08 17:25
Duplicate of #45.

**Comment by greg-1-anderson** [comment] 2017-03-08 17:27
That is to say, I think that you should implement append / prepend with an event handler, rather than having append / prepend explicitly provided as a Drupal Scaffold function.

Thought I answered this question a long time ago, but must have failed to finish typing up the answer. Sorry for the delay.

**Closed by greg-1-anderson** 2017-03-08 17:27 UTC
